=== juanBM-1122/homework_32/Archivos_Guia32_XML_Valido_DTD/EjercicioIII/ejercicio-iii.dtd
<!ELEMENT facultad (carrera)>
<!ELEMENT carrera (asignatura+)>
<!ELEMENT asignatura (grupoDeCatedra+)>
<!ELEMENT grupoDeCatedra (docente,asignacionEvaluada+)>
<!ELEMENT docente (#PCDATA)>
<!ELEMENT asignacionEvaluada (equipoDeTrabajo,a)>
<!ELEMENT equipoDeTrabajo (alumno+)>
<!ELEMENT alumno (#PCDATA)>
<!ELEMENT a (#PCDATA)>
<!ATTLIST facultad
universidad CDATA #FIXED "UNIVERSIDAD DE EL SALVADOR"
nombreFacultad CDATA #REQUIRED
codigoFacultad CDATA #REQUIRED>
<!ATTLIST carrera
nombreCarrera CDATA #REQUIRED
codigoCarrera CDATA #REQUIRED>
<!ATTLIST asignatura 
nombreAsignatura CDATA #REQUIRED
codigoAsignatura CDATA #REQUIRED>
<!ATTLIST grupoDeCatedra 
tipoDeGrupo CDATA #REQUIRED
numeroDeGrupo CDATA #REQUIRED>
<!ATTLIST docente 
nombres CDATA #REQUIRED
apellidos CDATA #REQUIRED
idProfesor CDATA #REQUIRED>
<!ATTLIST asignacionEvaluada 
tipoActividad CDATA #REQUIRED
ponderacion CDATA #REQUIRED>
<!ATTLIST equipoDeTrabajo
numeroDeGrupo CDATA #REQUIRED
temaAsignadao CDATA #REQUIRED>
<!ATTLIST alumno
nombre CDATA #REQUIRED
due CDATA #REQUIRED
apellidos CDATA #REQUIRED
coordinador (true|false) "false"
genero (M|F) "M">
<!ATTLIST a
href CDATA #IMPLIED
xmlns CDATA #IMPLIED
target CDATA ("_blank"|"_self") "_blank"
>

=== juanBM-1122/homework_32/Archivos_Guia32_XML_Valido_DTD/EjercicioIII/ejercicio-iii.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="./grupos.css"?>
<!DOCTYPE facultad SYSTEM "./ejercicio-iii.dtd">

<facultad nombreFacultad="facultad de ingenieria y arquitectura" codigoFacultad="FIA">

  <carrera nombreCarrera="Ingenieria en sistemas informaticos" codigoCarrera="I10515">
   <asignatura nombreAsignatura="Técnicas de programacion para internet" codigoAsignatura="TPI115">
    <grupoDeCatedra tipoDeGrupo="GT" numeroDeGrupo="01">
    <docente nombres="docente 01" apellidos="docente ap01" idProfesor="01">
    </docente>
    <asignacionEvaluada tipoActividad="Desarrollo de sistema" ponderacion="0.2">
     <equipoDeTrabajo numeroDeGrupo="01" temaAsignadao="Investigación SEO">
     <alumno nombre="alumno01" apellidos="al01" due="AZ09ddd" genero="F" coordinador="true">
     </alumno>
      <alumno nombre="alumno02" apellidos="al02" due="AZ09ddd" genero="M">
     </alumno>
      <alumno nombre="alumno03" apellidos="al03" due="AZ09ddd" genero="F">
     </alumno>
      <alumno nombre="alumno04" apellidos="al04" due="AZ09ddd" genero="M">
     </alumno>
     </equipoDeTrabajo>
      <a xmlns="http://www.w3.org/1999/xhtml" href="../../index.html">INICIO</a>
    </asignacionEvaluada>
    </grupoDeCatedra>   
   </asignatura>
  </carrera>
</facultad>
