<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="./css/estilo.css"?>
<!-- ejemplodtd1.xml -->

<!DOCTYPE fichero [
		<!ELEMENT fichero (ficha+)>
		<!ELEMENT ficha (nombre, apellido, direccion*, DUI?,a*)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
            	<!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>
		<!ELEMENT a (#PCDATA)>
		<!ATTLIST a 
		href CDATA #IMPLIED
		xmlns CDATA #IMPLIED
		target (_blank|_self|marco) "_blank">
		]>
<fichero>
 <ficha>
  <nombre sexo="femenino" edad="17">Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/Ulises, 36</direccion>
  <a xmlns="http://www.w3.org/1999/xhtml" href="../../../index.html">IR A INICIO</a>
 </ficha>
</fichero>
